[T-5618][FIX]Modification readmes project_stock_portal project_task_expense project_task_sign
sygel-technology/sy-project pull request #7
Opened 2024-02-29 11:50 UTC by Jaimermaccione

2024-02-29 11:50 UTC, Jaimermaccione commented
@ValentinVinagre @manuelregidor Revisar

2024-02-29 12:03 UTC, ValentinVinagre requested changes

2024-02-29 12:03 UTC, ValentinVinagre commented on project_stock_portal/README.rst
> -.. image:: https://pbs.twimg.com/profile_images/702799639855157248/ujffk9GL_200x200.png
@manuelregidor  y este link @Jaimermaccione ??? 
tiene que aparecer el de sygel. Por favor, cambiarlo y no solo lo borréis.

2024-02-29 12:03 UTC, ValentinVinagre commented on project_task_expense/README.rst
> -.. image:: https://pbs.twimg.com/profile_images/702799639855157248/ujffk9GL_200x200.png
mismo

2024-02-29 12:03 UTC, ValentinVinagre commented on project_task_sign/README.rst
> -.. image:: https://pbs.twimg.com/profile_images/702799639855157248/ujffk9GL_200x200.png
mismo

2024-03-01 07:35 UTC, Jaimermaccione commented
@ValentinVinagre Cambios hechos

2024-03-04 09:02 UTC, merged